version: '3.7'

services:
    minio:
        image: minio/minio
        restart: always
        ports:
            - "9000:9000"
        volumes: 
            - ./volumes/data:/data
        command: server /data